- hosts: servers
  remote_user: root
  tasks:
  - name: start server iperf
    shell: iperf --server --daemon

- hosts: clients
  remote_user: root
  serial: 1
  tasks:
  - name: set iperf server
    with_inventory_hostnames: ["servers"]
    set_fact: iperf_server="{{ item }}"
  
  - name: set output directory
    set_fact: output_dir="/tmp/iperf/"

  - name: print iperf server  
    debug:
      msg: "{{ iperf_server }}"

  - name: set output base
    set_fact: output_base="{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}_{{ iperf_server }}_{{ inventory_hostname }}.out"

  - name: set iperf out
    set_fact: iperf_out="iperf_{{ output_base }}"

  - name: set mtr out
    set_fact: mtr_out="mtr_{{ output_base }}"

  - name: print iperf out and mtr out
    debug:
      msg: 
       - "{{ iperf_out }}"
       - "{{ mtr_out }}"

  - name: start client iperf
    shell: "iperf --client {{ iperf_server }} --time 10 -i 1 -P 10 >> {{ iperf_out }}"

  - name: start client mtr
    shell: "/usr/sbin/mtr --report {{ iperf_server }} -c 10 >> {{ mtr_out }}"
 
  - name: grab iperf output
    fetch: src={{ iperf_out }} dest={{ output_dir }} flat=yes

  - name: grab mtr output
    fetch: src={{ mtr_out }} dest={{ output_dir }} flat=yes

- hosts: servers
  remote_user: root
  tasks:
  - name: kill iperf
    shell: "pkill -x iperf"
                                
- hosts: localhost              
  connection: local             
  tasks:                        
  - name: print results directory
    debug:
       msg: " Results directory is /tmp/iperf "
